{% set name = "osqp-eigen" %}
{% set version = "0.8.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/robotology/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 21f04878bed68cb433c4341570ee2e5755f7d499d8ab550e7dc2308569dabf71

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  host:
    - libosqp
    - eigen
  run:
    - eigen

test:
  commands:
    - test -f ${PREFIX}/include/OsqpEigen/OsqpEigen.h  # [not win]
    - test -f ${PREFIX}/lib/cmake/OsqpEigen/OsqpEigenConfig.cmake  # [not win]
    - test -f ${PREFIX}/lib/libOsqpEigen${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\include\\OsqpEigen\\OsqpEigen.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\OsqpEigen.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\OsqpEigen.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\OsqpEigen\\OsqpEigenConfig.cmake exit 1  # [win]
    - cmake-package-check OsqpEigen
  requires:
    - cmake-package-check
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://github.com/robotology/osqp-eigen
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simple C++ wrapper for osqp library.

extra:
  recipe-maintainers:
    - GiulioRomualdi
    - traversaro
