schema_version: 1

context:
  name: osqp-eigen
  version: "0.11.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/robotology/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 731f9242f7144a652268a2c4cf1e38b6b18b9ac582c065a63ce9d5c491877a3a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - ninja
    - cmake
  host:
    - libosqp
    - eigen
    - eigen-abi-devel
  run:
    - eigen
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - package_contents:
      include:
        - OsqpEigen/OsqpEigen.h
      lib:
        - OsqpEigen
      files:
        - "**/cmake/OsqpEigen/OsqpEigenConfig.cmake"
  - requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
    script:
      - cmake-package-check OsqpEigen --targets OsqpEigen::OsqpEigen

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Simple C++ wrapper for osqp library.
  homepage: https://github.com/robotology/osqp-eigen

extra:
  recipe-maintainers:
    - GiulioRomualdi
    - traversaro
